name: todo_app
description: Todo App using Firebase Auth, Realtime Database and BLoC
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  google_sign_in: ^6.2.1

  # BLoC
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.5

  # HTTP
  http: ^1.2.2

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  fluttertoast: ^9.0.0
  flutter_slidable: ^4.0.3
  animate_do: ^4.2.0

  # Utils
  uuid: ^4.4.2
  intl: ^0.20.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

#  assets:
#  - assets/images/
#  - assets/animations/
