// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6lM-VOGwb-3kR9HmsxuwU7ITJzo274XU',
    appId: '1:63833441556:android:0244a7abacb1781d6aee01',
    messagingSenderId: '63833441556',
    projectId: 'todo-list-b3dfc',
    storageBucket: 'todo-list-b3dfc.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlIWTIH9fQUtbLFJEF4vT74yQi6HvvUJQ',
    appId: '1:63833441556:web:8a0195a87968be1b6aee01',
    messagingSenderId: '63833441556',
    projectId: 'todo-list-b3dfc',
    authDomain: 'todo-list-b3dfc.firebaseapp.com',
    storageBucket: 'todo-list-b3dfc.firebasestorage.app',
    measurementId: 'G-YK9ZVHWP4K',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATtgIkKkzDry-nOMr6EsNP2OqjwEdI-mo',
    appId: '1:63833441556:ios:de4d6309905fdd076aee01',
    messagingSenderId: '63833441556',
    projectId: 'todo-list-b3dfc',
    storageBucket: 'todo-list-b3dfc.firebasestorage.app',
    iosBundleId: 'y',
  );

}